
#####################database PostgreSql stagging######################
spring.datasource.url=jdbc:postgresql://pg-262bd0cb-chandudibyajyotisahoo-e5b7.a.aivencloud.com:19906/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_76J8QKFisHQ_-z9Y6Ox
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=test_secret_key_minimum_32_characters_long
app.jwt.expiration-ms=3600000
app.admin.password=testpass
cloudinary.folder=Nkp
app.cors.allowed-origins=http://localhost:3000

